added test to precommit hook

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -10,5 +10,18 @@ if [ $CHECKSTYLE_STATUS -ne 0 ]; then
     exit 1 
 fi
 
-echo "✅ Linter checks passed! Proceeding with your commit..."
+echo "✅ Linter checks passed! Proceeding with runnign tests..."
+
+echo "Running Tests..."
+
+mvn test
+TEST_STATUS=$?
+
+if [ $TEST_STATUS -ne 0 ]; then
+    echo "❌ Tests failed! Fix your errors before committing buddy!"
+    exit 1 
+fi
+
+echo "✅ Tests passed! Proceeding with commit..."
+
 exit 0
